### ISSUE TITLE
Firefox Extension and play in order

### ISSUE THREAD

**Issue by DonFlymoor** [Tyson3101/Auto-Youtube-Shorts-Scroller#22]
I use firefox because of chrome's new draconian policies, so I would love to see this extension for it.
Also, having the ability to play a creator's shorts in order from oldest to newest or most popular to least popular would be great

**Comment by Tyson3101** [comment]
Hey, For Firefox, someone has ported this extension to there but it doesn't seem to be getting updates as of late (It's only like 2 minor versions behind).
[Firefox Addon](https://addons.mozilla.org/en-US/firefox/addon/auto-youtube-shorts-scroller/)

And for your suggestion, in terms of popular to least popular shorts, you can achieve that by going to creators 'shorts' tab on their channel, and click the 'popular' chip/button.
To sort oldest to newest, I have found [this firefox add-on](https://addons.mozilla.org/en-US/firefox/addon/sort-by-oldest/) that adds a sort by oldest to shorts.
And when you click on the top short when sorted, the shorts will be in order, so the extension can work as usual.

Because of these methods, I doubt I'll add the sorting integrated into the extension, unless I see more people wanting it.
